### ISSUE TITLE
[Milestone] Jam version

### ISSUE THREAD

**Issue by oultrox** [oultrox/Game-off-Not-Time-For-Crisis#4]
- [ ]  Introducción del juego tanto visual como de lore.

- [ ] El outro del demo final, visualmente lo más pro posible.

- [ ] El final del combate para cuando ganemos  y cuando perdamos.

- [ ] El muro rompible;

- [ ] El sistema de perks tanto visual como logico ya funcionando completamente con las armas y pasivas.

- [ ] Diálogos necesarios en las interacciones estipuladas ya listos.

- [ ] La siguiente zona en donde se encontrará un Boss y posteriormente al derrotarlo damos por terminado "el primer capítulo" con el outro. 

- [ ] Inventario o más bien panel visual de nuestra munición

- [ ] Sistema (HUD) visual de la experiencia y el leveleo;

- [ ] SFX y música implementada para las zonas necesarias;
